# Generated by Django 5.1.6 on 2025-09-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('focus_lost', 'Focus Lost'), ('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('phone_detected', 'Phone Detected'), ('notes_detected', 'Notes Detected'), ('device_detected', 'Device Detected'), ('drowsiness', 'Drowsiness Detected'), ('audio_anomaly', 'Audio Anomaly')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score for the detection (0-1)')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='interviews.interview')),
            ],
        ),
    ]
