# Generated by Django 5.1.6 on 2025-09-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('focus_loss_count', models.IntegerField(default=0)),
                ('suspicious_events', models.IntegerField(default=0)),
                ('integrity_score', models.IntegerField(default=100, help_text='Integrity score out of 100')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('face_detection_accuracy', models.FloatField(default=0.0, help_text='Face detection accuracy (0-1)')),
                ('audio_quality_score', models.FloatField(default=0.0, help_text='Audio quality score (0-1)')),
                ('focus_lost_events', models.IntegerField(default=0)),
                ('no_face_events', models.IntegerField(default=0)),
                ('multiple_faces_events', models.IntegerField(default=0)),
                ('phone_detected_events', models.IntegerField(default=0)),
                ('notes_detected_events', models.IntegerField(default=0)),
                ('device_detected_events', models.IntegerField(default=0)),
                ('drowsiness_events', models.IntegerField(default=0)),
                ('audio_anomaly_events', models.IntegerField(default=0)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviews.interview')),
            ],
        ),
    ]
