# Generated by Django 5.2.7 on 2025-11-01 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interview_options_alter_videorecording_options_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='csv_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='last_exported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='overall_assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('disputed', 'Disputed')], default='final', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['integrity_score'], name='reports_rep_integri_28fce1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_at'], name='reports_rep_generat_35ba4e_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['candidate_name'], name='reports_rep_candida_d8ad39_idx'),
        ),
    ]
