# Generated by Django 5.0.6 on 2025-09-18 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interview',
            name='title',
            field=models.CharField(default='Interview Session', max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
